@startuml
skinparam ArrowFontStyle plain

actor User
participant ":PharmaTracker" as PharmaTracker
participant ":Ui" as Ui
participant "<<class>>\nParser" as Parser
participant "c:FindCommand" as FindCommand
participant "inv:Inventory" as Inventory
participant "med:Medication" as Medication
participant ":System.out" as Console

User -> PharmaTracker : "find paracetamol"
activate PharmaTracker

PharmaTracker -> Ui : readCommand()
activate Ui
Ui --> PharmaTracker : fullCommand
deactivate Ui

PharmaTracker -> Parser : parse(fullCommand)
activate Parser

create FindCommand
Parser -> FindCommand : new FindCommand(keyword)
activate FindCommand
FindCommand --> Parser : c
deactivate FindCommand

Parser --> PharmaTracker : c
deactivate Parser

PharmaTracker -> FindCommand : execute(inv, ui, customerList)
activate FindCommand

FindCommand -> Inventory : getMedications()
activate Inventory
Inventory --> FindCommand : medicationList
deactivate Inventory

loop for each medication
    FindCommand -> Medication : getName()
    activate Medication
    Medication --> FindCommand : name
    deactivate Medication

    alt name contains keyword
        FindCommand -> FindCommand : matchingMedications.add(med)
        activate FindCommand
        FindCommand --> FindCommand
        deactivate FindCommand
    end
end

alt no matching medications found
    FindCommand -> Console : println("No medications found matching: ...")
    activate Console
    Console --> FindCommand
    deactivate Console
else matches found
    FindCommand -> Ui : printFindResults(matchingMedications)
    activate Ui
    Ui --> FindCommand
    deactivate Ui
end

FindCommand --> PharmaTracker
deactivate FindCommand
FindCommand -[hidden]-> Parser
destroy FindCommand

deactivate PharmaTracker
@enduml
