@startuml
skinparam ArrowFontStyle plain
skinparam maxMessageSize 100

actor User
participant ":PharmaTracker" as PharmaTracker
participant ":Ui" as Ui
participant "<<class>>\nPharmaTrackerParser" as PTP
participant "parser:UpdateCommandParser" as UpdateParser
participant "<<class>>\nMedicationParserUtil" as MedParserUtil
participant "u:UpdateCommand" as UpdateCommand
participant "inv:Inventory" as Inventory
participant "med:Medication" as Medication

User -> PharmaTracker : "update 1 /q 50"
activate PharmaTracker

PharmaTracker -> Ui : readCommand()
activate Ui
Ui --> PharmaTracker : fullCommand
deactivate Ui

PharmaTracker -> PTP : parse(fullCommand)
activate PTP

create UpdateParser
PTP -> UpdateParser : new UpdateCommandParser()
activate UpdateParser
UpdateParser --> PTP : parser
deactivate UpdateParser

PTP -> UpdateParser : parse("1 /q 50")
activate UpdateParser

UpdateParser -> MedParserUtil : extractOptionalQuantity("1 /q 50")
activate MedParserUtil
MedParserUtil --> UpdateParser : quantity = 50
deactivate MedParserUtil

note right of UpdateParser
  Other optional flags are extracted
  using ParserUtil.extractOptionalFlag()
  and MedicationParserUtil.extractWarnings()
end note

create UpdateCommand
UpdateParser -> UpdateCommand : new UpdateCommand(1, null, null, 50, ...)
activate UpdateCommand
UpdateCommand --> UpdateParser : u
deactivate UpdateCommand

UpdateParser --> PTP : u
deactivate UpdateParser
destroy UpdateParser

PTP --> PharmaTracker : u
deactivate PTP

PharmaTracker -> UpdateCommand : execute(inv, ui, customerList)
activate UpdateCommand

UpdateCommand -> Inventory : getMedication(0)
activate Inventory
Inventory --> UpdateCommand : med
deactivate Inventory

opt [quantity != null]
    UpdateCommand -> Medication : setQuantity(50)
    activate Medication
    Medication --> UpdateCommand
    deactivate Medication
end

note right of UpdateCommand
  Other non-null fields are updated
  via their respective setters and added
  to the 'changes' list.
end note

UpdateCommand -> Ui : printUpdatedMedicationMessage(med, changes)
activate Ui
Ui --> UpdateCommand
deactivate Ui

UpdateCommand --> PharmaTracker
deactivate UpdateCommand
destroy UpdateCommand

PharmaTracker --> User : output
deactivate PharmaTracker
@enduml